// Typical U.S. school-cafeteria portions with approximate nutrition, based on
// USDA FoodData Central and common school food-service product specs.
// Values are estimates for one standard serving as it's usually plated.
//
// Fields: kcal, p/c/f = protein/carbs/fat in grams. `aliases` are matched
// against menu text (lowercase, "&" becomes "and"); the longest alias wins, so
// "chicken caesar salad" beats "chicken". `generic` marks catch-all rows that
// only give a ballpark when nothing more specific matched.

const food = (id, name, portion, kcal, p, c, f, aliases, extra = {}) => ({
  id,
  name,
  portion,
  kcal,
  p,
  c,
  f,
  aliases,
  ...extra,
})

export const FOOD_DB = [
  // ── Pizza & Italian ─────────────────────────────────────────────
  food('cheese-pizza', 'Cheese pizza', '1 slice', 300, 15, 36, 11, ['pizza', 'cheese pizza', 'pizza slice', 'flatbread pizza', 'deep dish pizza', 'cheesy pizza']),
  food('pepperoni-pizza', 'Pepperoni pizza', '1 slice', 330, 15, 35, 14, ['pepperoni pizza', 'pepperoni']),
  food('sausage-pizza', 'Sausage pizza', '1 slice', 340, 16, 35, 15, ['sausage pizza', 'supreme pizza', 'meat lovers pizza', 'chicken pizza']),
  food('breakfast-pizza', 'Breakfast pizza', '1 slice', 280, 13, 28, 13, ['breakfast pizza']),
  food('french-bread-pizza', 'French bread pizza', '1 piece', 350, 16, 42, 13, ['french bread pizza']),
  food('calzone', 'Calzone / stromboli', '1 piece', 480, 22, 52, 20, ['calzone', 'stromboli', 'pizza pocket', 'hot pocket']),
  food('spaghetti', 'Spaghetti with meat sauce', '1.5 cups', 420, 20, 58, 12, ['spaghetti', 'spaghetti with meat sauce', 'meat sauce', 'bolognese', 'chicken bolognese', 'veg bolognese', 'veg bolognese sauce']),
  food('spaghetti-meatballs', 'Spaghetti & meatballs', '1.5 cups + 3 meatballs', 520, 24, 62, 19, ['spaghetti and meatballs', 'spaghetti with meatballs', 'meatballs']),
  food('lasagna', 'Lasagna', '1 piece', 380, 22, 34, 17, ['lasagna', 'lasagne']),
  food('baked-ziti', 'Baked ziti', '1.5 cups', 450, 21, 52, 17, ['baked ziti', 'ziti', 'pasta bake', 'baked penne', 'rigatoni']),
  food('pasta-marinara', 'Pasta with marinara', '1.5 cups', 330, 11, 62, 4, ['pasta', 'marinara', 'penne', 'rotini', 'arrabiata', 'arrabbiata', 'penne arrabiata', 'penne arrabbiata', 'red sauce pasta'], { generic: true }),
  food('chicken-alfredo', 'Chicken alfredo', '1.5 cups', 560, 30, 52, 25, ['chicken alfredo', 'fettuccine alfredo', 'fettuccine']),
  food('chicken-parm', 'Chicken parmesan', '1 piece + ½ cup pasta', 520, 34, 48, 20, ['chicken parmesan', 'chicken parm', 'chicken parmigiana']),
  food('mac-cheese', 'Macaroni & cheese', '1 cup', 380, 15, 44, 16, ['mac and cheese', 'macaroni and cheese', 'mac n cheese', 'macaroni', 'mac cheese']),
  food('garlic-bread', 'Garlic bread / breadstick', '1 piece', 150, 4, 20, 6, ['garlic bread', 'breadstick', 'bread stick', 'garlic toast', 'texas toast', 'garlic knot']),
  food('cheesy-breadstick', 'Cheesy breadstick', '1 piece', 200, 9, 22, 8, ['cheese breadstick', 'cheesy breadstick', 'cheesy bread', 'stuffed breadstick']),

  // ── Burgers, sandwiches & hand-helds ────────────────────────────
  food('cheeseburger', 'Cheeseburger', '1 sandwich', 350, 19, 32, 16, ['cheeseburger', 'cheese burger', 'double cheeseburger', 'bacon cheeseburger']),
  food('hamburger', 'Hamburger', '1 sandwich', 300, 16, 31, 12, ['hamburger', 'burger', 'beef burger']),
  food('sliders', 'Sliders', '2 sliders', 360, 18, 32, 17, ['slider', 'sliders', 'mini burgers', 'chicken sliders', 'veg sliders']),
  food('veggie-burger', 'Veggie burger', '1 sandwich', 320, 16, 40, 10, ['veggie burger', 'black bean burger', 'garden burger', 'veg burger']),
  food('chicken-sandwich', 'Crispy chicken sandwich', '1 sandwich', 420, 20, 42, 19, ['chicken sandwich', 'crispy chicken sandwich', 'spicy chicken sandwich', 'chicken patty', 'chicken patty sandwich', 'fried chicken sandwich', 'chicken burger']),
  food('grilled-chicken-sandwich', 'Grilled chicken sandwich', '1 sandwich', 330, 26, 34, 9, ['grilled chicken sandwich', 'grilled chicken burger']),
  food('chicken-biscuit', 'Chicken biscuit', '1 sandwich', 420, 18, 38, 22, ['chicken biscuit']),
  food('hot-dog', 'Hot dog', '1 with bun', 290, 11, 24, 17, ['hot dog', 'hotdog', 'frank', 'chili dog']),
  food('corn-dog', 'Corn dog', '1 corn dog', 250, 8, 26, 13, ['corn dog', 'corndog', 'mini corn dogs']),
  food('grilled-cheese', 'Grilled cheese', '1 sandwich', 370, 14, 32, 21, ['grilled cheese', 'grilled cheese sandwich']),
  food('pbj', 'PB&J sandwich', '1 sandwich', 380, 13, 46, 17, ['pb and j', 'pbj', 'peanut butter and jelly', 'peanut butter jelly', 'peanut butter sandwich']),
  food('uncrustable', 'Uncrustables (PB&J)', '1 sandwich', 210, 6, 26, 10, ['uncrustable', 'uncrustables']),
  food('turkey-sandwich', 'Turkey sandwich', '1 sandwich', 300, 20, 32, 9, ['turkey sandwich', 'turkey and cheese', 'turkey and cheese sandwich', 'deli sandwich']),
  food('ham-sandwich', 'Ham & cheese sandwich', '1 sandwich', 330, 19, 32, 13, ['ham sandwich', 'ham and cheese', 'ham and cheese sandwich']),
  food('sub', 'Sub / hoagie', '6-inch', 330, 20, 42, 9, ['sub', 'hoagie', 'sub sandwich', 'turkey sub', 'ham sub', 'italian sub', 'hoagie sandwich']),
  food('meatball-sub', 'Meatball sub', '6-inch', 480, 22, 50, 21, ['meatball sub', 'meatball sandwich', 'meatball hoagie']),
  food('sandwich', 'Sandwich', '1 sandwich', 350, 17, 36, 14, ['sandwich', 'veg sandwich', 'brown bread sandwich', 'bread sandwich'], { generic: true }),
  food('wrap', 'Chicken wrap', '1 wrap', 450, 25, 38, 21, ['wrap', 'chicken wrap', 'chicken caesar wrap', 'buffalo chicken wrap']),
  food('sloppy-joe', 'Sloppy joe', '1 sandwich', 330, 17, 36, 12, ['sloppy joe', 'sloppy joes']),
  food('pulled-pork', 'BBQ pulled pork sandwich', '1 sandwich', 420, 24, 44, 15, ['pulled pork', 'bbq pork', 'bbq sandwich', 'rib sandwich', 'rib b q', 'bbq rib']),
  food('cheesesteak', 'Philly cheesesteak', '1 sandwich', 480, 28, 42, 22, ['philly cheesesteak', 'cheesesteak', 'cheese steak', 'philly']),
  food('breakfast-sandwich', 'Breakfast sandwich', '1 sandwich', 420, 16, 30, 26, ['breakfast sandwich', 'sausage biscuit', 'sausage egg and cheese', 'egg and cheese biscuit', 'croissant sandwich', 'breakfast biscuit', 'egg sandwich']),

  // ── Chicken, meat & fish ────────────────────────────────────────
  food('nuggets', 'Chicken nuggets', '6 pieces', 280, 14, 17, 17, ['chicken nuggets', 'nuggets', 'chicken nugget', 'nugs', 'dino nuggets']),
  food('tenders', 'Chicken tenders', '3 pieces', 290, 18, 18, 16, ['chicken tenders', 'tenders', 'chicken strips', 'chicken fingers', 'chicken tenderloins', 'strips']),
  food('popcorn-chicken', 'Popcorn chicken', '1 cup', 300, 15, 20, 18, ['popcorn chicken', 'chicken bites']),
  food('wings', 'Boneless wings', '6 pieces', 360, 20, 24, 20, ['wings', 'chicken wings', 'boneless wings', 'buffalo wings', 'hot wings']),
  food('baked-chicken', 'Baked / grilled chicken', '1 piece (3 oz)', 180, 26, 0, 8, ['chicken', 'baked chicken', 'grilled chicken', 'roast chicken', 'roasted chicken', 'chicken breast', 'chicken drumstick', 'chicken leg', 'bbq chicken', 'herb chicken', 'lemon pepper chicken'], { generic: true }),
  food('fried-chicken', 'Fried chicken', '1 piece', 290, 20, 10, 19, ['fried chicken', 'crispy chicken', 'chicken thigh']),
  food('orange-chicken', 'Orange chicken', '1 cup', 400, 18, 42, 18, ['orange chicken', 'general tso', 'general tsos chicken', 'sesame chicken', 'sweet and sour chicken', 'mandarin chicken']),
  food('teriyaki-chicken', 'Teriyaki chicken', '1 cup', 280, 26, 22, 9, ['teriyaki chicken', 'teriyaki', 'chicken teriyaki']),
  food('stir-fry', 'Chicken stir fry', '1 cup', 250, 20, 18, 10, ['stir fry', 'chicken stir fry', 'beef stir fry', 'kung pao chicken', 'kung pao', 'asian style chicken', 'chicken and broccoli', 'tai pai chicken', 'asian style chicken and broccoli']),
  food('pot-pie', 'Chicken pot pie', '1 pie', 450, 15, 40, 26, ['pot pie', 'chicken pot pie']),
  food('fish-sticks', 'Fish sticks', '5 sticks', 290, 13, 25, 15, ['fish sticks', 'fish sandwich', 'fish nuggets', 'fish fillet', 'fish', 'fish and chips', 'fish tacos', 'crumb fried fish', 'fried fish', 'fish fingers']),
  food('meatloaf', 'Meatloaf', '1 slice', 280, 19, 12, 17, ['meatloaf', 'meat loaf']),
  food('salisbury-steak', 'Salisbury steak', '1 patty', 290, 17, 10, 20, ['salisbury steak', 'hamburger steak', 'country fried steak', 'chicken fried steak']),
  food('pork-chop', 'Pork chop', '1 chop', 220, 26, 0, 12.5, ['pork chop', 'pork loin', 'pork']),
  food('turkey', 'Roast turkey', '3 oz', 150, 25, 0, 5, ['turkey', 'roast turkey', 'sliced turkey']),
  food('ham', 'Baked ham', '3 oz', 140, 18, 3, 6, ['ham', 'baked ham', 'sliced ham']),

  // ── Mexican-style ───────────────────────────────────────────────
  food('tacos', 'Beef tacos', '2 tacos', 360, 18, 26, 20, ['taco', 'tacos', 'beef taco', 'beef tacos', 'hard shell taco', 'soft taco', 'street tacos', 'taco tuesday']),
  food('chicken-tacos', 'Chicken tacos', '2 tacos', 320, 22, 28, 12, ['chicken taco', 'chicken tacos', 'chicken street tacos']),
  food('beef-burrito', 'Burrito', '1 burrito', 470, 22, 52, 19, ['burrito', 'beef burrito', 'chicken burrito', 'beef and bean burrito']),
  food('bean-burrito', 'Bean & cheese burrito', '1 burrito', 400, 16, 56, 12, ['bean burrito', 'bean and cheese burrito', 'veg burrito']),
  food('breakfast-burrito', 'Breakfast burrito', '1 burrito', 320, 14, 30, 16, ['breakfast burrito', 'egg burrito']),
  food('quesadilla', 'Cheese quesadilla', '1 quesadilla', 420, 18, 36, 22, ['quesadilla', 'cheese quesadilla']),
  food('chicken-quesadilla', 'Chicken quesadilla', '1 quesadilla', 480, 28, 36, 24, ['chicken quesadilla']),
  food('nachos', 'Nachos with cheese', '1 tray', 450, 12, 48, 23, ['nachos', 'nacho', 'nacho supreme', 'nachos grande', 'chips and cheese']),
  food('walking-taco', 'Walking taco', '1 bag', 420, 15, 38, 23, ['walking taco', 'frito pie']),
  food('taco-salad', 'Taco salad', '1 bowl', 500, 24, 36, 29, ['taco salad', 'taco bowl']),
  food('burrito-bowl', 'Burrito / rice bowl', '1 bowl', 550, 28, 72, 15, ['burrito bowl', 'rice bowl', 'chicken bowl', 'grain bowl', 'bowl'], { generic: true }),
  food('enchiladas', 'Enchiladas', '2 enchiladas', 420, 20, 36, 22, ['enchilada', 'enchiladas']),
  food('fajitas', 'Fajitas', '2 fajitas', 380, 24, 38, 14, ['fajita', 'fajitas', 'chicken fajitas']),
  food('tamale', 'Tamale', '1 tamale', 280, 9, 26, 16, ['tamale', 'tamales']),

  // ── Soups & salads ──────────────────────────────────────────────
  food('chili', 'Chili', '1 cup', 260, 18, 24, 10, ['chili', 'chili con carne', 'turkey chili']),
  food('soup', 'Soup', '1 cup', 150, 6, 18, 5, ['soup', 'chicken noodle soup', 'tomato soup', 'vegetable soup', 'minestrone', 'chicken noodle', 'chowder', 'corn chowder', 'tom yum', 'manchow', 'hot and sour soup', 'rasam', 'shorba', 'broth', 'dal shorba', 'tomato shorba', 'sweet corn soup', 'sweet corn veg soup', 'cream of carrot soup', 'cream of broccoli soup', 'cream of tomato soup', 'cream of spinach', 'cream of spinach soup', 'leeks potato soup', 'leek potato soup', 'potato soup', 'tomato basil broth', 'pumpkin soup', 'cabbage chowder'], { generic: true }),
  food('side-salad', 'Side salad (no dressing)', '1 cup', 20, 1, 4, 0.2, ['salad', 'side salad', 'green salad', 'garden salad', 'tossed salad', 'julienne salad', 'onion salad', 'laccha onion salad', 'kachumber', 'lettuce', 'romaine', 'salad bar', 'carrot and raisin salad', 'green bean salad', 'grilled veg salad', 'fattoush', 'caprese salad', 'karedok salad'], { generic: true }),
  food('caesar-salad', 'Caesar salad', '1 side', 190, 5, 9, 15, ['caesar salad', 'caesar']),
  food('chicken-caesar', 'Chicken caesar salad', '1 entrée salad', 380, 28, 14, 24, ['chicken caesar salad', 'chicken caesar', 'grilled chicken salad', 'crispy chicken salad']),
  food('chef-salad', 'Chef salad', '1 entrée salad', 330, 24, 10, 22, ['chef salad', 'chefs salad', 'cobb salad']),
  food('ranch', 'Salad dressing (ranch)', '1 packet (1 oz)', 140, 0.5, 2, 14.5, ['ranch', 'ranch dressing', 'dressing', 'italian dressing']),
  food('coleslaw', 'Coleslaw', '½ cup', 150, 1, 13, 10.5, ['coleslaw', 'cole slaw', 'slaw', 'coleslaw salad']),

  // ── Breakfast ───────────────────────────────────────────────────
  food('pancakes', 'Pancakes', '3 mini', 250, 6, 40, 7, ['pancakes', 'pancake', 'mini pancakes', 'pancake bites', 'pan cake', 'american pan cake', 'american pancake']),
  food('waffles', 'Waffles', '2 mini', 200, 4, 30, 7, ['waffles', 'waffle', 'mini waffles', 'waffle bites']),
  food('french-toast', 'French toast sticks', '5 sticks', 350, 6, 45, 16, ['french toast', 'french toast sticks']),
  food('syrup', 'Syrup', '1 cup (1 oz)', 100, 0, 25, 0, ['syrup', 'maple syrup']),
  food('cereal', 'Cereal', '1 bowl (1 oz)', 110, 2, 24, 1, ['cereal', 'cheerios', 'frosted flakes', 'cinnamon toast crunch', 'froot loops', 'fruit loops', 'rice krispies cereal']),
  food('oatmeal', 'Oatmeal', '1 cup', 160, 6, 28, 3, ['oatmeal', 'oats', 'overnight oats']),
  food('grits', 'Grits', '1 cup', 150, 3.5, 32, 0.5, ['grits']),
  food('yogurt', 'Yogurt (low-fat)', '4 oz', 110, 5, 19, 1.5, ['yogurt', 'yoghurt', 'gogurt', 'go gurt', 'greek yogurt']),
  food('parfait', 'Yogurt parfait', '1 cup', 220, 8, 38, 4, ['parfait', 'yogurt parfait']),
  food('bagel', 'Bagel', '1 bagel', 280, 11, 55, 1.5, ['bagel', 'bagels']),
  food('bagel-cream-cheese', 'Bagel with cream cheese', '1 bagel', 360, 12, 56, 10, ['bagel with cream cheese', 'bagel and cream cheese', 'cream cheese']),
  food('muffin', 'Muffin', '1 muffin', 340, 5, 48, 14, ['muffin', 'muffins', 'blueberry muffin', 'banana muffin', 'banana bread', 'zucchini bread']),
  food('scrambled-eggs', 'Scrambled eggs', '2 eggs', 180, 12, 2, 14, ['eggs', 'egg', 'scrambled eggs', 'scrambled egg']),
  food('sausage', 'Sausage', '1 patty / 2 links', 180, 8, 1, 16, ['sausage', 'sausage patty', 'sausage links', 'sausage link']),
  food('bacon', 'Bacon', '2 slices', 90, 6, 0, 7, ['bacon', 'turkey bacon']),
  food('hash-brown', 'Hash brown', '1 patty', 150, 1, 15, 9, ['hash brown', 'hash browns', 'hashbrown', 'hashbrowns', 'tater patty', 'hash brown potato', 'hash brown potatoes']),
  food('biscuits-gravy', 'Biscuits & gravy', '1 serving', 380, 9, 40, 20, ['biscuits and gravy', 'biscuit and gravy', 'sausage gravy']),
  food('biscuit', 'Biscuit', '1 biscuit', 200, 4, 25, 9, ['biscuit', 'biscuits']),
  food('cinnamon-roll', 'Cinnamon roll', '1 roll', 360, 6, 52, 14, ['cinnamon roll', 'cinnamon bun', 'cinni mini', 'cinnamon rolls']),
  food('pop-tart', 'Pop-Tart', '1 pastry', 200, 2, 37, 5, ['pop tart', 'pop tarts', 'poptart', 'toaster pastry']),
  food('donut', 'Donut', '1 glazed', 240, 3, 30, 12, ['donut', 'doughnut', 'donuts', 'doughnuts']),
  food('toast', 'Toast with butter', '1 slice', 110, 3, 13, 5, ['toast', 'buttered toast']),
  food('granola-bar', 'Granola / cereal bar', '1 bar', 130, 2, 24, 3.5, ['granola bar', 'cereal bar', 'breakfast bar', 'nutrigrain', 'nutri grain']),

  // ── Sides & starches ────────────────────────────────────────────
  food('fries', 'French fries', '1 serving', 230, 3, 31, 11, ['fries', 'fry', 'french fries', 'curly fries', 'waffle fries', 'seasoned fries', 'crinkle fries']),
  food('sweet-potato-fries', 'Sweet potato fries', '1 serving', 200, 2, 28, 9, ['sweet potato fries']),
  food('tater-tots', 'Tater tots', '9 tots', 190, 2, 22, 10, ['tater tots', 'tots', 'tater tot', 'potato tots']),
  food('mashed-potatoes', 'Mashed potatoes', '½ cup', 110, 2, 17, 4, ['mashed potatoes', 'mashed potato', 'potatoes', 'whipped potatoes']),
  food('gravy', 'Gravy', '¼ cup', 30, 1, 3, 1.5, ['gravy', 'brown gravy', 'chicken gravy']),
  food('baked-potato', 'Baked potato', '1 medium', 160, 4, 37, 0.2, ['baked potato', 'potato']),
  food('loaded-potato', 'Loaded baked potato', '1 medium', 350, 12, 40, 16, ['loaded baked potato', 'loaded potato', 'stuffed potato']),
  food('roasted-potatoes', 'Roasted potatoes', '½ cup', 150, 2, 20, 7, ['roasted potatoes', 'roast potatoes', 'oven roast potatoes', 'potato wedges', 'wedges', 'home fries', 'oven potatoes', 'seasoned potatoes', 'potato rounds', 'potato bravas', 'patatas bravas', 'bravas', 'dry pot potatoes', 'sichuan dry pot potatoes', 'roasted potato wedges']),
  food('sweet-potato', 'Sweet potato', '½ cup', 90, 2, 21, 0.2, ['sweet potato', 'sweet potatoes', 'yams']),
  food('rice', 'Rice', '1 cup', 205, 4, 45, 0.4, ['rice', 'white rice', 'steamed rice', 'brown rice']),
  food('fried-rice', 'Fried rice', '1 cup', 240, 6, 34, 9, ['fried rice', 'vegetable fried rice']),
  food('spanish-rice', 'Spanish rice', '½ cup', 130, 3, 25, 2, ['spanish rice', 'mexican rice', 'rice pilaf', 'cilantro lime rice', 'yellow rice']),
  food('lo-mein', 'Lo mein', '1 cup', 300, 10, 42, 10, ['lo mein', 'chow mein', 'stir fry noodles', 'curried noodles', 'hakka noodles', 'noodles']),
  food('refried-beans', 'Refried beans', '½ cup', 120, 7, 18, 2, ['refried beans']),
  food('baked-beans', 'Baked beans', '½ cup', 170, 6, 29, 3, ['baked beans', 'pork and beans', 'bbq beans']),
  food('beans', 'Black / pinto beans', '½ cup', 110, 7, 20, 0.5, ['beans', 'black beans', 'pinto beans', 'ranch style beans', 'kidney beans', 'chickpeas']),
  food('cornbread', 'Cornbread', '1 piece', 180, 3, 28, 6, ['cornbread', 'corn bread', 'corn muffin']),
  food('roll', 'Dinner roll', '1 roll', 110, 3, 19, 2, ['roll', 'rolls', 'dinner roll', 'bread roll', 'multigrain bread roll', 'brown onion bread roll', 'wheat roll', 'slice of bread', 'whole grain roll']),
  food('chips', 'Chips', '1 bag (1 oz)', 140, 2, 18, 7, ['chips', 'tortilla chips', 'doritos', 'baked chips', 'lays', 'sun chips', 'sunchips', 'fritos', 'baked doritos', 'cheetos', 'baked cheetos']),
  food('salsa', 'Salsa', '2 tbsp', 10, 0.5, 2, 0, ['salsa', 'pico de gallo', 'pico']),
  food('egg-roll', 'Egg roll', '1 roll', 200, 6, 22, 10, ['egg roll', 'spring roll', 'egg rolls']),
  food('pretzel', 'Soft pretzel', '1 pretzel', 170, 5, 34, 1.5, ['soft pretzel', 'pretzel', 'pretzels', 'pretzel bites']),
  food('mozz-sticks', 'Mozzarella sticks', '3 sticks', 280, 12, 22, 16, ['mozzarella sticks', 'mozz sticks', 'mozzarella stick']),
  food('string-cheese', 'String cheese', '1 stick', 80, 7, 1, 6, ['string cheese', 'cheese stick', 'cheese sticks', 'mozzarella string cheese']),
  food('hummus', 'Hummus', '2 oz', 100, 4, 8, 6, ['hummus', 'hummus cup']),

  // ── Vegetables ──────────────────────────────────────────────────
  food('corn', 'Corn', '½ cup', 75, 2.5, 15, 1, ['corn', 'sweet corn', 'sweetcorn', 'buttered corn', 'kernel corn', 'whole kernel corn', 'corn salad', 'sweetcorn salad']),
  food('corn-cob', 'Corn on the cob', '1 ear', 95, 3, 19, 1.3, ['corn on the cob', 'corn cob', 'corn cobbette', 'cobbette']),
  food('green-beans', 'Green beans', '½ cup', 25, 1, 5, 0.1, ['green beans', 'string beans', 'green bean']),
  food('broccoli', 'Broccoli', '½ cup', 30, 2, 5, 0.3, ['broccoli', 'steamed broccoli', 'broccoli florets']),
  food('carrots', 'Carrots', '½ cup', 30, 0.6, 7, 0.1, ['carrots', 'carrot', 'baby carrots', 'carrot sticks', 'carrot coins', 'glazed carrots']),
  food('mixed-veg', 'Mixed vegetables', '½ cup', 55, 2.5, 11, 0.2, ['mixed vegetables', 'mixed veggies', 'vegetables', 'veggies', 'veggie medley', 'vegetable medley', 'peas and carrots', 'california blend', 'steamed vegetables', 'veggie cup'], { generic: true }),
  food('peas', 'Green peas', '½ cup', 60, 4, 11, 0.3, ['peas', 'green peas', 'sweet peas']),
  food('celery', 'Celery sticks', '½ cup', 10, 0.4, 2, 0.1, ['celery', 'celery sticks']),
  food('cucumber', 'Cucumber slices', '½ cup', 8, 0.3, 2, 0.1, ['cucumber', 'cucumbers', 'cucumber slices']),
  food('side-veg-generic', 'Cooked vegetables', '½ cup', 40, 2, 8, 0.3, ['spinach', 'zucchini', 'squash', 'cauliflower', 'brussels sprouts', 'kale', 'collard greens', 'greens', 'asparagus']),

  // ── Fruit ───────────────────────────────────────────────────────
  food('apple', 'Apple', '1 medium', 95, 0.5, 25, 0.3, ['apple', 'apples', 'apple slices', 'fresh apple']),
  food('banana', 'Banana', '1 medium', 105, 1.3, 27, 0.4, ['banana', 'bananas']),
  food('orange', 'Orange', '1 medium', 62, 1.2, 15, 0.2, ['orange', 'oranges', 'orange slices', 'orange wedges', 'mandarin', 'mandarin oranges', 'clementine', 'cuties']),
  food('grapes', 'Grapes', '1 cup', 105, 1, 27, 0.2, ['grapes', 'grape']),
  food('fruit-cup', 'Fruit cup', '½ cup', 60, 0.5, 15, 0, ['fruit', 'fruit cup', 'mixed fruit', 'fruit cocktail', 'peaches', 'diced peaches', 'pears', 'diced pears', 'pineapple', 'fresh fruit', 'fruit salad', 'fruit choice', 'assorted fruit', 'seasonal fruit', 'guava', 'pomegranate', 'chikoo'], { generic: true }),
  food('berries', 'Strawberries / berries', '1 cup', 50, 1, 12, 0.5, ['strawberries', 'strawberry', 'berries', 'blueberries', 'mixed berries']),
  food('melon', 'Melon', '1 cup', 50, 1, 11.5, 0.2, ['watermelon', 'cantaloupe', 'melon', 'honeydew']),
  food('applesauce', 'Applesauce', '½ cup', 50, 0, 13, 0, ['applesauce', 'apple sauce', 'applesauce cup']),
  food('raisins', 'Raisins / dried fruit', '1 box (1 oz)', 85, 1, 22, 0, ['raisins', 'dried cranberries', 'craisins', 'dried fruit']),

  // ── Drinks ──────────────────────────────────────────────────────
  food('milk', '1% milk', '8 fl oz', 105, 8, 12, 2.5, ['milk', 'white milk', '1 milk', 'low fat milk', 'lowfat milk', 'skim milk', 'fat free milk', 'nonfat milk', '2 milk']),
  food('choc-milk', 'Chocolate milk (fat-free)', '8 fl oz', 130, 8, 23, 0.5, ['chocolate milk', 'choc milk', 'strawberry milk', 'flavored milk', 'fat free chocolate milk']),
  food('juice', '100% juice', '4 fl oz', 60, 0.5, 14.5, 0, ['juice', 'orange juice', 'apple juice', 'juice box', '100 juice', 'fruit juice', 'grape juice']),
  food('smoothie', 'Smoothie', '12 fl oz', 220, 6, 46, 1.5, ['smoothie', 'fruit smoothie', 'yogurt smoothie']),

  // ── Desserts & snacks ───────────────────────────────────────────
  food('cookie', 'Cookie', '1 large', 200, 2, 27, 10, ['cookie', 'cookies', 'chocolate chip cookie', 'sugar cookie', 'oatmeal cookie', 'oatmeal raisin cookie', 'snickerdoodle', 'butter cookies', 'jam drop cookies', 'honey oats cookies', 'oats cookies', 'ragi cookies', 'ragi jaggery cookies']),
  food('brownie', 'Brownie', '1 square', 230, 3, 32, 11, ['brownie', 'brownies', 'blondie']),
  food('rice-krispie', 'Rice Krispies treat', '1 bar', 90, 1, 17, 2.5, ['rice krispie treat', 'rice krispies treat', 'krispie treat', 'rice crispy treat']),
  food('cake', 'Cake with frosting', '1 slice', 300, 3, 45, 12, ['cake', 'cupcake', 'sheet cake', 'birthday cake', 'chocolate cake', 'pastry', 'coffee cake', 'mud cake', 'vanilla pastry', 'chocolate pastry', 'brownie cake', 'banana cake', 'carrot and raisin cake', 'dates and raisins cake', 'belgian chocolate cake', 'columbian coffee cake', 'black forest cake', 'mississippi mud cake', 'swiss roll', 'strawberry swiss roll', 'butterscotch pastry', 'muffin cake']),
  food('pudding', 'Pudding', '4 oz cup', 130, 2.5, 22, 3.5, ['pudding', 'chocolate pudding', 'vanilla pudding', 'pudding cup']),
  food('jello', 'Jell-O', '4 oz cup', 70, 1.5, 17, 0, ['jello', 'jell o', 'gelatin', 'jelly']),
  food('ice-cream', 'Ice cream', '4 oz cup / bar', 150, 3, 20, 7, ['ice cream', 'ice cream cup', 'ice cream sandwich', 'frozen yogurt', 'fudge bar', 'sundae cup']),
  food('popsicle', 'Popsicle / fruit bar', '1 bar', 60, 0, 15, 0, ['popsicle', 'fruit bar', 'fruit juice bar', 'freeze pop', 'italian ice', 'slushie']),
  food('churro', 'Churro', '1 churro', 160, 2, 20, 8, ['churro', 'churros']),
  food('crackers', 'Crackers / Goldfish', '1 pack (1 oz)', 140, 3, 20, 5, ['goldfish', 'crackers', 'cheez its', 'cheez it', 'cheezits', 'graham crackers', 'teddy grahams', 'animal crackers', 'cheese crackers']),
  food('fruit-snacks', 'Fruit snacks', '1 pouch', 80, 0.5, 19, 0, ['fruit snacks', 'fruit snack', 'gummies']),
  // ── Indian school lunch (typical canteen portions) ─────────────
  // Breads
  food('chapati', 'Chapati / roti', '1 piece', 105, 3, 18, 2.5, ['chapati', 'chapatti', 'roti', 'phulka', 'chapati roti']),
  food('aloo-paratha', 'Aloo paratha', '1 paratha', 290, 6, 40, 12, ['aloo paratha', 'paratha', 'potato paratha', 'gobi paratha']),
  food('paneer-paratha', 'Paneer paratha', '1 paratha', 320, 11, 36, 15, ['paneer paratha']),
  food('bhatura', 'Bhatura', '1 bhatura', 300, 6, 38, 14, ['bhatura', 'bhature', 'chole bhature']),
  food('pav', 'Pav (bun)', '1 bun', 150, 5, 27, 2.5, ['pav', 'pav bun', 'ladi pav', 'pao']),
  // Rice
  food('jeera-rice', 'Jeera rice', '1 cup', 240, 4, 44, 5, ['jeera rice', 'cumin rice']),
  food('jollof-rice', 'Jollof rice', '1 cup', 280, 5, 48, 7, ['jollof rice', 'jollof']),
  food('pulao', 'Veg pulao / biryani', '1 cup', 290, 6, 45, 9, ['pulao', 'pulav', 'veg pulao', 'biryani', 'veg biryani', 'tagine rice', 'paneer biryani']),
  // Dals & legumes
  food('dal', 'Dal (tadka / plain)', '1 bowl', 180, 9, 26, 5, ['dal', 'daal', 'dhal', 'dal tadka', 'dal dhokli', 'dal fry', 'amti dal', 'arahar dal', 'arhar dal', 'toor dal', 'moong dal', 'masoor dal', 'varan dal', 'kathiawadi dal', 'mangodi ki dal', 'batla dal', 'khasi style dal', 'palak dal', 'dal bhukara', 'dal mughlai', 'hawaijor dal', 'lentil curry', 'lentils', 'dalcha', 'dosakaya pappu', 'pappu', 'gongura dal', 'dal tamatar', 'madra dal', 'khar dal', 'gahat dal', 'dal maharaja', 'dal pakhwan', 'amritsari dal', 'dal tadkewali', 'hawaijar dal']),
  food('dal-makhani', 'Dal makhani', '1 bowl', 280, 11, 28, 14, ['dal makhani', 'dal makhni', 'daal makhani', 'maa ki dal']),
  food('sambar', 'Sambar', '1 bowl', 140, 6, 20, 4, ['sambar', 'sambhar']),
  food('chole', 'Chole masala', '1 bowl', 270, 11, 36, 9, ['chole', 'chole masala', 'chana masala', 'pindi chole', 'chickpea curry', 'channa masala', 'chana palak']),
  food('rajma', 'Rajma masala', '1 bowl', 240, 12, 34, 6, ['rajma', 'rajma masala', 'rajma chawal']),
  food('lobia', 'Lobia masala', '1 bowl', 220, 11, 30, 6, ['lobia', 'lobia masala', 'black eyed peas', 'chawli']),
  food('sundal', 'Chana sundal', '½ cup', 150, 7, 22, 4, ['sundal', 'chana sundal', 'black chana sundal', 'black chana', 'kala chana']),
  food('sprouts', 'Sprouts salad / kosumbari', '1 cup', 110, 7, 18, 1.5, ['sprouts', 'sprouts salad', 'kosumbari', 'moong salad']),
  // Paneer
  food('paneer-butter-masala', 'Paneer butter masala', '1 bowl', 400, 16, 14, 31, ['paneer', 'paneer butter masala', 'paneer makhani', 'paneer tikka masala', 'shahi paneer', 'kadai paneer', 'kadhai paneer', 'paneer jalfrezi']),
  food('palak-paneer', 'Palak paneer', '1 bowl', 280, 14, 12, 20, ['palak paneer', 'saag paneer']),
  food('mutter-paneer', 'Mutter paneer', '1 bowl', 300, 14, 16, 20, ['mutter paneer', 'matar paneer', 'mattar paneer']),
  food('chilli-paneer', 'Chilli paneer', '1 bowl', 330, 15, 20, 21, ['chilli paneer', 'chilly paneer', 'chili paneer']),
  food('paneer-tikka', 'Paneer tikka', '6 pieces', 280, 18, 8, 20, ['paneer tikka']),
  // Vegetable curries & snacks
  food('bhindi', 'Bhindi (okra) sabzi', '1 bowl', 150, 3, 14, 10, ['bhindi', 'bhindi do pyaza', 'dahi bhindi', 'bhindi masala', 'okra']),
  food('aloo', 'Aloo sabzi / dum aloo', '1 bowl', 230, 4, 30, 11, ['aloo', 'dum aloo', 'dum aloo banarasi', 'aloo sabzi', 'aloo gobi', 'aloo tindly', 'aloo tindly fry', 'jeera aloo', 'aloo matar', 'aloo bhaji', 'aloo chaat', 'aloo palya', 'bombay sagu', 'sagu', 'rajasthani aloo curry', 'rajastani aloo curry', 'jaiphali aloo']),
  food('sabzi', 'Mixed veg curry / sabzi', '1 bowl', 180, 5, 16, 11, ['sabzi', 'sabji', 'mix veg', 'veg curry', 'vegetable curry', 'gobi', 'gobi makhani', 'dhingri gobi makhani', 'phool makhana', 'phool makhana masala', 'makhana', 'jalfrezi', 'veg kolhapuri', 'navratan korma', 'kofta', 'malai kofta', 'vegetable option', 'chilli gobi', 'methi mutter masala', 'methi matar', 'mushroom masala', 'mushroom and capsicum masala', 'veg jaipuri', 'veg jalfrezi', 'kobi bhatata nu shaak', 'shaak', 'undhiyu', 'gujarati undhiyu', 'aloo capsicum masala', 'gobi mutter']),
  food('kadhi', 'Kadhi pakora', '1 bowl', 260, 8, 22, 15, ['kadhi', 'kadi', 'kadi pakodi', 'kadhi pakora', 'kadhi pakoda']),
  food('litti-choka', 'Litti choka', '2 litti + choka', 420, 12, 58, 15, ['litti choka', 'litti']),
  food('bhaji', 'Veg bhaji', '1 bowl', 220, 5, 26, 11, ['bhaji', 'veg bhaji', 'bhaaji']),
  food('pav-bhaji', 'Pav bhaji', 'bhaji + 2 pav', 520, 13, 80, 16, ['pav bhaji']),
  food('vada-pav', 'Vada pav', '1 vada pav', 300, 7, 40, 12, ['vada pav', 'wada pav', 'vadapav']),
  food('pakora', 'Pakora', '4 pieces', 250, 6, 22, 15, ['pakora', 'pakoda', 'pakodi', 'bhajiya', 'maakouda', 'onion pakora', 'medu pakora']),
  food('samosa', 'Samosa', '1 samosa', 260, 5, 30, 13, ['samosa', 'samosas']),
  food('veg-tagine', 'Veg tagine / stew', '1 bowl', 200, 5, 28, 8, ['tagine', 'veg tagine', 'stew', 'veg stew']),
  food('shakshuka', 'Shakshuka', '1 serving (2 eggs)', 250, 14, 12, 16, ['shakshuka', 'saksuka', 'shakshouka', 'turkish saksuka', 'menemen']),
  food('baked-veg', 'Baked corn & spinach', '1 cup', 260, 9, 20, 16, ['baked corn', 'baked corn and spinach', 'corn and spinach', 'baked vegetables', 'au gratin', 'baked veg']),
  food('kung-pao-tofu', 'Kung pao tofu', '1 bowl', 280, 15, 18, 17, ['kung pao tofu', 'tofu', 'chilli tofu', 'tofu stir fry']),
  food('dumplings', 'Veg dumplings / momos', '6 pieces', 240, 7, 36, 7, ['dumplings', 'dumpling', 'momos', 'momo', 'veg dumplings', 'dim sum']),
  food('butter-chicken', 'Butter chicken / chicken curry', '1 bowl', 400, 28, 10, 28, ['butter chicken', 'chicken curry', 'chicken tikka masala', 'chicken masala', 'murgh makhani', 'kadai chicken', 'chicken makhani', 'chicken korma', 'chicken khorma', 'shredded chicken masala']),
  food('banh-mi', 'Banh mi', '1 sandwich', 450, 20, 55, 16, ['banh mi', 'bahn mi']),
  food('pasta-alfredo', 'Pasta alfredo (white sauce)', '1.5 cups', 480, 14, 56, 22, ['pasta alfredo', 'alfredo pasta', 'white sauce pasta', 'alfredo']),
  food('pink-pasta', 'Pink sauce pasta', '1.5 cups', 430, 13, 58, 16, ['pink sauce pasta', 'pink pasta', 'rose pasta', 'rosa pasta']),
  food('russian-salad', 'Russian salad (mayo)', '½ cup', 200, 3, 14, 15, ['russian salad', 'potato salad', 'macaroni salad', 'waldorf salad', 'potato corn salad']),
  food('grain-salad', 'Couscous / grain salad', '1 cup', 180, 5, 30, 4.5, ['couscous', 'couscous salad', 'barley salad', 'quinoa salad', 'grain salad', 'bulgur salad', 'tabbouleh', 'tabouli']),
  food('idli', 'Idli', '2 idli', 130, 4, 26, 0.8, ['idli', 'idly']),
  food('dosa', 'Plain dosa', '1 dosa', 170, 4, 28, 4.5, ['dosa', 'plain dosa']),
  food('masala-dosa', 'Masala dosa', '1 dosa', 330, 7, 45, 13, ['masala dosa']),
  food('poha', 'Poha', '1 cup', 250, 5, 40, 8, ['poha']),
  food('upma', 'Upma', '1 cup', 250, 6, 36, 9, ['upma', 'rava upma', 'rava kitchadi', 'rava kichadi']),
  // Accompaniments
  food('papad', 'Papad', '1 papad', 45, 2.5, 6, 1.2, ['papad', 'papadum', 'poppadom', 'appalam']),
  food('pickle', 'Pickle (achar)', '1 tbsp', 30, 0.2, 1, 3, ['pickle', 'achar', 'achaar']),
  food('curd', 'Curd (dahi)', '½ cup', 60, 3.5, 4.5, 3.3, ['curd', 'dahi', 'plain curd']),
  food('raita', 'Raita', '½ cup', 70, 3, 6, 3.5, ['raita', 'boondi raita']),
  // Morning snacks & drinks
  food('small-banana', 'Small banana', '1 small', 90, 1.1, 23, 0.3, ['small banana']),
  food('indian-biscuits', 'Biscuits (assorted)', '2 biscuits', 110, 1.5, 16, 4.5, ['assorted biscuits', 'marie', 'marie biscuits', 'parle g', 'cream biscuits', 'digestive biscuits']),
  food('coffee', 'Coffee with milk & sugar', '1 cup (150 ml)', 70, 2.5, 10, 2.5, ['coffee', 'milk coffee', 'filter coffee']),
  food('lemon-drink', 'Lemon juice / iced tea / sharbat', '1 glass (200 ml)', 80, 0, 20, 0, ['lemon juice', 'ginger lemon juice', 'mint lemon juice', 'sweet n salt lemon juice', 'sweet and salt lemon juice', 'nimbu pani', 'lemonade', 'iced tea', 'ice tea', 'lemon ice tea', 'lemon iced tea', 'sharbat', 'sarbath', 'sharbath', 'lemon sarbath', 'lemon sharbat', 'watermelon lemon sarbath', 'watermelon and lemon sarbath', 'watermelon and lemon sharbat', 'watermelon lemon sharbat', 'jaljeera']),
  food('mango-juice', 'Mango juice', '1 glass (200 ml)', 110, 0.2, 28, 0, ['mango juice', 'mango drink', 'maaza', 'frooti', 'mango shake']),
  food('coconut-water', 'Paper Boat coconut water', '100 ml pack', 22, 0.2, 5.3, 0, ['paper boat', 'paper boat coconut water', 'coconut water', 'tender coconut', 'nariyal pani']),
  // Indian desserts
  food('ladoo', 'Ladoo (boondi / motichoor)', '1 ladoo', 185, 2.5, 25, 8.5, ['ladoo', 'laddu', 'laddoo', 'boondi ladoo', 'motichoor ladoo', 'besan ladoo']),
  food('gulab-jamun', 'Gulab jamun', '2 pieces', 300, 4, 44, 12, ['gulab jamun', 'gulab jamoon', 'jamun']),
  food('rasmalai', 'Rasmalai', '2 pieces', 250, 8, 30, 11, ['rasmalai', 'ras malai']),
  food('chum-chum', 'Chum chum / rasgulla', '1 piece', 150, 3, 28, 3, ['chum chum', 'cham cham', 'rasgulla', 'rosogolla', 'sandesh', 'champakali']),
  food('burfi', 'Burfi / peda', '1 piece', 130, 3, 18, 5, ['burfi', 'barfi', 'mango burfi', 'peda', 'dharwad peda', 'kalakand', 'mysore pak']),
  food('kheer', 'Kheer / payasam', '½ cup', 200, 5, 30, 6.5, ['kheer', 'payasam', 'rice pudding', 'phirni', 'sheer khurma', 'phirnee', 'firni', 'moong dal payasam', 'semiya payasam', 'sabudana kheer']),
  food('shahi-tukda', 'Zauq-e-shahi / shahi tukda', '1 serving', 350, 6, 42, 17, ['zauq e shahi', 'shahi tukda', 'double ka meetha', 'bread pudding']),
  food('apple-crumble', 'Apple crumble', '1 serving', 300, 3, 45, 12, ['apple crumble', 'crumble', 'apple pie', 'cobbler']),
  // ── Full-day school menu (breakfast, snacks, dinner) ───────────
  // Breakfast
  food('poori', 'Poori', '2 pooris', 200, 4, 24, 10, ['poori', 'puri', 'pooris']),
  food('chutney', 'Coconut chutney', '2 tbsp', 60, 1, 3, 5, ['chutney', 'coconut chutney', 'green chutney']),
  food('medu-vada', 'Medu vada / masala vada', '2 vadas', 260, 8, 26, 14, ['vada', 'medu vada', 'masala vada', 'maddur vada', 'dal vada']),
  food('bonda', 'Bonda / bajji', '2 pieces', 240, 5, 26, 13, ['bonda', 'mysore bonda', 'aloo bonda', 'bajji', 'mixed veg bajji', 'capsicum bajji', 'mirchi bajji']),
  food('chow-chow-bath', 'Chow chow bath (khara + kesari bath)', '1 plate', 450, 8, 62, 19, ['chow chow bath', 'khara bath', 'kesari bath']),
  food('uttapam', 'Uttapam', '1 uttapam', 230, 6, 36, 7, ['uttapam', 'uthappam', 'plain uttapam', 'onion uttapam']),
  food('adai', 'Adai (lentil dosa)', '1 adai', 220, 9, 30, 7, ['adai', 'pesarattu']),
  food('sannas', 'Sannas (steamed rice cakes)', '2 pieces', 180, 3.5, 36, 2, ['sannas', 'masala sannas', 'appam']),
  food('avial', 'Avial', '1 bowl', 180, 4, 14, 12, ['avial', 'aviyal']),
  food('thepla', 'Methi thepla', '2 theplas', 240, 6, 32, 10, ['thepla', 'methi thepla']),
  food('dhokla', 'Khaman dhokla', '3 pieces', 180, 7, 26, 5.5, ['dhokla', 'khaman dhokla', 'khaman']),
  food('muthiya', 'Dudhi muthiya', '4 pieces', 200, 5, 26, 8.5, ['muthiya', 'dudhi muthiya', 'muthia']),
  food('mathri', 'Dal mathri', '3 pieces', 210, 4, 22, 12, ['mathri', 'matri', 'dal matri', 'dal mathri']),
  food('rusk', 'Rusk', '2 rusks', 120, 3, 20, 3, ['rusk', 'rusks', 'barley malt rusk', 'toast rusk']),
  food('swirl-bun', 'Multigrain swirl bun', '1 bun', 230, 6, 36, 7, ['multigrain swirl', 'swirl', 'swirl bun', 'sweet bun']),
  food('lavash', 'Whole wheat lavash sticks', '3 sticks (30 g)', 130, 4, 22, 3, ['lavash', 'lavash stick', 'lavash sticks', 'whole wheat lavash stick']),
  food('aloo-tikki', 'Aloo tikki / veg cutlet', '2 pieces', 240, 4, 28, 12.5, ['aloo tikki', 'tikki', 'veg cutlet', 'cutlet', 'veg croquettes', 'croquettes', 'croquette']),
  food('omelette', 'Omelette (plain / masala)', '2 eggs', 190, 13, 3, 14, ['omelette', 'omelet', 'plain omelette', 'masala omelette', 'spanish omelette', 'egg omelette']),
  food('cheese-omelette', 'Cheese omelette', '2 eggs', 260, 17, 2, 20.5, ['cheese omelette', 'cheese omelet']),
  food('boiled-egg', 'Boiled egg', '1 egg', 78, 6.3, 0.6, 5.3, ['boiled egg', 'hard boiled egg', 'egg boiled']),
  food('fried-egg', 'Fried egg', '1 egg', 90, 6.3, 0.4, 7, ['fried egg', 'sunny side up', 'egg fried']),
  food('cornflakes', 'Corn flakes with milk', '1 bowl (30 g + 200 ml milk)', 230, 9, 36, 5.5, ['corn flakes', 'cornflakes', 'choco flakes', 'chocos', 'cereal with milk']),
  food('muesli', 'Muesli with milk', '1 bowl (45 g + 200 ml milk)', 290, 12, 44, 8, ['muesli']),
  food('bread', 'Bread (white / brown / multigrain)', '2 slices', 160, 5.5, 29, 2, ['bread', 'brown bread', 'multigrain bread', 'white bread', 'bread slice', 'bread slices']),
  food('butter', 'Butter', '1 pat (5 g)', 36, 0, 0, 4, ['butter', 'butter pat']),
  food('cheese-spread', 'Cheese spread', '1 tbsp', 45, 2, 1.5, 3.5, ['cheese spread', 'cheese slice']),
  food('jam', 'Jam', '1 tbsp', 55, 0, 14, 0, ['jam', 'fruit jam', 'mixed fruit jam']),
  food('papaya', 'Papaya', '1 cup', 60, 0.7, 15, 0.4, ['papaya']),
  food('fresh-juice', 'Fresh fruit juice', '1 glass (200 ml)', 100, 1, 24, 0.3, ['fresh fruit juice', 'fresh juice', 'orange juice fresh', 'mosambi juice']),
  // Drinks
  food('tea', 'Tea with milk & sugar', '1 cup (150 ml)', 60, 2, 9, 2, ['tea', 'chai', 'masala chai', 'milk tea']),
  food('malt-drink', 'Boost / Bournvita / hot chocolate', '1 cup (200 ml milk)', 180, 8, 26, 5, ['boost', 'bournvita', 'hot chocolate', 'horlicks', 'milo', 'malt drink']),
  food('flavoured-milk', 'Flavoured milk (badam / kesar / dates)', '1 glass (200 ml)', 200, 7, 28, 6.5, ['badam milk', 'kesar milk', 'dates milk', 'banana milk', 'strawberry milk', 'rose milk', 'flavoured milk', 'flavored milk', 'milkshake']),
  food('buttermilk', 'Buttermilk (chaas)', '1 glass (200 ml)', 40, 2.5, 4, 1.5, ['buttermilk', 'butter milk', 'chaas', 'chhaas', 'masala chaas']),
  food('cold-coffee', 'Cold coffee', '1 glass (250 ml)', 190, 6, 28, 6, ['cold coffee', 'iced coffee', 'frappe']),
  // Snacks
  food('puff', 'Puff / fatayer / vol-au-vent', '2 pieces', 300, 6, 26, 19, ['puff', 'puffs', 'veg puff', 'paneer and capsicum puffs', 'fatayer', 'spinach and cheese fatayer', 'vol au vent', 'veg vol au vent']),
  food('croissant', 'Croissant', '1 croissant', 300, 5.5, 32, 17, ['croissant', 'croissants', 'chocolate croissant', 'chocolate croissants']),
  food('stuffed-bun', 'Stuffed bun (aloo bun / masala roll)', '1 bun', 250, 6, 36, 9, ['aloo bun', 'masala roll', 'masala rolls', 'bun', 'dilpasand', 'dilkhush']),
  food('choco-balls', 'Chocolate balls', '2 pieces', 180, 2.5, 22, 9.5, ['choco balls', 'chocolate balls', 'truffles', 'rum balls']),
  // Dinner breads & sides
  food('naan', 'Butter naan', '1 naan', 320, 9, 48, 10, ['naan', 'butter naan', 'garlic naan']),
  food('kulcha', 'Amritsari kulcha', '1 kulcha', 330, 8, 48, 12, ['kulcha', 'amritsari kulcha', 'stuffed kulcha']),
  food('lachha-paratha', 'Lachha / multigrain paratha', '1 paratha', 260, 5, 34, 11.5, ['lachha paratha', 'laccha paratha', 'plain paratha', 'multigrain paratha']),
  food('pan-con-tomate', 'Pan con tomate', '2 slices', 220, 5, 30, 9, ['pan con tomato', 'pan con tomate', 'bruschetta']),
  food('tartar-sauce', 'Tartar sauce / mayo', '1 tbsp', 70, 0.2, 2, 7, ['tartar sauce', 'mayonnaise', 'mayo']),
  food('saute-veg', 'Sautéed / stir-fried veg (poriyal)', '1 cup', 120, 3, 12, 7, ['saute veg', 'sauteed veg', 'sauteed vegetables', 'oriental saute veg', 'buttered veg', 'buttered vegetables', 'poriyal', 'mixed veg poriyal', 'foogath', 'cabbage foogath', 'thoran', 'tawa subzi', 'tawa sabzi', 'stir fry veg', 'asian stir fry veg']),
  // Dinner curries
  food('bagara-baingan', 'Bagara baingan / mirchi ka salan', '1 bowl', 260, 5, 14, 21, ['bagara baingan', 'hyderabadi bagara baingan', 'baingan', 'brinjal curry', 'baingan bharta', 'mirchi ka salan', 'salan']),
  food('soya-masala', 'Soya chunks masala', '1 bowl', 230, 18, 16, 10, ['soya', 'soya chunks', 'soya chunks masala', 'soya mutter masala', 'soya chunk curry', 'meal maker']),
  food('usal', 'Usal (sprouts curry)', '1 bowl', 220, 11, 28, 7, ['usal', 'maharashtrian usal', 'maharastrian usal', 'misal']),
  food('manchurian', 'Veg manchurian', '1 bowl', 300, 6, 30, 17, ['manchurian', 'veg manchurian', 'gobi manchurian']),
  food('paneer-bhurji', 'Paneer bhurji', '1 bowl', 330, 18, 8, 25, ['paneer bhurji']),
  food('egg-masala', 'Egg masala curry', '1 bowl (2 eggs)', 280, 14, 10, 20, ['egg masala', 'egg curry', 'anda curry']),
  // Non-veg
  food('tandoori-chicken', 'Tandoori chicken', '2 pieces', 300, 36, 5, 15, ['tandoori chicken', 'chicken tikka', 'tandoori']),
  food('grilled-fish', 'Grilled fish, lemon butter sauce', '1 fillet', 260, 30, 2, 14.5, ['grilled fish', 'grilled fish with lemon butter sauce', 'lemon butter fish']),
  food('chicken-keema', 'Chicken keema', '1 bowl', 330, 26, 10, 21, ['keema', 'kheema', 'chicken keema', 'chicken kheema', 'chicken kheema mutter', 'keema matar']),
  food('chicken-fried-rice', 'Chicken fried rice', '1.5 cups', 420, 18, 58, 13, ['chicken fried rice', 'egg fried rice']),
  food('biryani', 'Chicken / mutton biryani', '1.5 cups', 480, 24, 58, 17, ['chicken biryani', 'chicken dum biryani', 'mutton biryani', 'dum biryani', 'egg biryani']),
  food('chicken-cutlet', 'Chicken cutlets', '2 pieces', 300, 18, 18, 17, ['chicken cutlet', 'chicken cutlets']),
  food('bao', 'Bao buns', '2 buns', 360, 14, 46, 13, ['bao', 'bao bun', 'bao buns', 'chicken bao buns', 'veg and paneer bao buns', 'steamed buns']),
  // Desserts
  food('halwa', 'Halwa', '½ cup', 300, 4, 38, 15, ['halwa', 'halva', 'moong dal halwa', 'white pumpkin halwa', 'gajar halwa', 'sooji halwa', 'sheera']),
  food('jalebi', 'Jalebi', '2 pieces (50 g)', 190, 1, 30, 7.5, ['jalebi', 'imarti']),
]

export const FOOD_BY_ID = Object.fromEntries(FOOD_DB.map((item) => [item.id, item]))
