// The school's full-day cyclic menus for 2026–27 (from the Week 1–3 PDFs):
// early morning snack + breakfast, morning snacks + lunch, afternoon/evening
// snacks + dinner. Each row is "CATEGORY|Mon|Tue|Wed|Thu|Fri|Sat|Sun" with
// blanks for days without that item. They work without any upload and sit
// alongside uploaded weeks (an upload for the same week replaces them).

const SPECIAL_LUNCH = 'FRIDAY SPECIAL LUNCH'
const SPECIAL_DINNER = 'WEDNESDAY SPECIAL DINNER'

const every = (cat, text, skip = []) => [cat, ...Array.from({ length: 7 }, (_, d) => (skip.includes(d) ? '' : text))].join('|')
const WED = [2]
const FRI = [4]

// Shared rows that are the same every week.
const BREAKFAST_BREAD =
  'BREAD|BREAD/BROWN BREAD|BREAD/BROWN BREAD|BREAD/BROWN BREAD|BREAD/MULTIGRAIN BREAD|BREAD/MULTIGRAIN BREAD|BREAD/BROWN BREAD|BREAD/BROWN BREAD'
const BREAKFAST_END = [
  every('BREAD', 'TOAST'),
  every('ACCOMPANIMENTS', 'JAM'),
  every('BEVERAGE', 'COLD MILK'),
  every('BEVERAGE', 'TEA'),
  every('BEVERAGE', 'COFFEE'),
]
const MORNING_END = [every('BISCUITS', 'ASSORTED BISCUITS'), every('FRUIT', 'SMALL BANANA'), every('BEVERAGE', 'COFFEE')]
const LUNCH_END = [
  every('RICE', 'PLAIN RICE', FRI),
  every('ACCOMPANIMENTS', 'PAPAD', FRI),
  every('ACCOMPANIMENTS', 'PICKLE', FRI),
  every('ACCOMPANIMENTS', 'CURD', FRI),
  every('FRUIT', 'SEASONAL FRUIT', FRI),
]
const dinnerEnd = (curd) => [
  every('RICE', 'PLAIN RICE', WED),
  every('ACCOMPANIMENTS', 'PAPAD', WED),
  every('ACCOMPANIMENTS', 'PICKLE', WED),
  curd,
  every('FRUIT', 'SEASONAL FRUIT', WED),
]

const RAW = [
  {
    week: 1,
    weekStart: '2026-10-05',
    breakfast: [
      'EARLY SNACK|BOOST|HOT CHOCOLATE|PLAIN HOT MILK|BOOST|PLAIN HOT MILK||',
      'EARLY SNACK|CARROT & RAISIN CAKE|BARLEY MALT RUSK|WHOLE WHEAT BANANA CAKE|BROWN BREAD SANDWICH|DUDHI MUTHIYA||',
      'MAIN|IDLY|ALOO PARATHA|MINI BHATURA|ALOO POHA|POORI|CHOW CHOW BATH|MASALA DOSA',
      'MAIN|MEDU VADA|PICKLE|CHOLE MASALA|MYSORE BONDA|ALOO BHAJI||ALOO PALYA',
      'MAIN|SAMBAR|CURD||CHUTNEY||CHUTNEY|SAMBAR',
      'MAIN|CHUTNEY|||BAKED BEANS|||CHUTNEY',
      'CONTI|FRENCH TOAST|AMERICAN PAN CAKE|FRENCH TOAST|AMERICAN PAN CAKE|FRENCH TOAST|AMERICAN PAN CAKE|VEG SANDWICH',
      'CONTI|MAPLE SYRUP|MAPLE SYRUP|MAPLE SYRUP|CHOCOLATE SYRUP|MAPLE SYRUP|MAPLE SYRUP|',
      'EGG|CHEESE OMELETTE|SCRAMBLED EGG|FRIED EGG|MASALA OMELETTE|CHEESE OMELETTE|PLAIN OMELETTE|BOILED EGG',
      'CEREAL|HASH BROWN POTATO|CORN FLAKES|CORN FLAKES|HASH BROWN POTATO|CORN FLAKES|CORN FLAKES|CORN FLAKES',
      'CEREAL|CORN FLAKES/MUESLI|MUESLI|MUESLI|CHOCO FLAKES|MUESLI|MUESLI|MUESLI',
      'FRUIT|BANANA|PAPAYA|BANANA|PAPAYA|BANANA|FRESH FRUIT JUICE|FRESH FRUIT JUICE',
      BREAKFAST_BREAD,
      'ACCOMPANIMENTS|BUTTER|BUTTER /CHEESE SPREAD|BUTTER|BUTTER /CHEESE SPREAD|BUTTER|BUTTER /CHEESE SPREAD|BUTTER',
      'BEVERAGE|BOOST|HOT CHOCOLATE|BOOST|HOT CHOCOLATE|BOOST|HOT CHOCOLATE|BOOST',
    ],
    morning: ['JUICE|GINGER LEMON JUICE|ICED TEA|WATERMELON & LEMON SARBATH|SWEET N SALT LEMON JUICE|ICED TEA|MINT LEMON JUICE|MANGO JUICE'],
    lunch: [
      'SOUP|RASAM|TOMATO SOUP||SWEET CORN VEG SOUP||MANCHOW SOUP|TOMATO PEPPER RASAM',
      'SALAD|JULIENNE SALAD|SPROUTS SALAD|GREEN SALAD|RUSSIAN SALAD||SALAD NICOISE|ONION SALAD',
      'BREAD|CHAPATI|VADA PAV|CHAPATI|CHAPATI||ALOO PARATHA|BHATURA',
      'BREAD||||MULTIGRAIN BREAD ROLL||MULTIGRAIN BREAD ROLL|POTATO BRAVAS',
      'CONTI MAIN|JOLLOF RICE|ORIENTAL SAUTE VEG|KIMCHI FRIED RICE|PINK SAUCE PASTA||BAKED CORN & SPINACH|CHOLE MASALA',
      'INDIAN VEG|BHINDI DO PYAZA|SUBZI KADHI|PANEER TIKKA MASALA|VEG JALFREZI||DHINGRI GOBI MAKHANI|SHREDDED CHICKEN MASALA',
      'LENTIL|DAL TADKA|DAL MAKHANI|SAMBAR|MASALA DAL||KATHIAWADI DAL|VARAN DAL',
      'DESSERT|PHIRNEE|EGGLESS VANILLA PASTRY|ICE CREAM|BOONDI LADOO||CHUM CHUM|BELGIAN CHOCOLATE CAKE',
    ],
    lunchSpecial: SPECIAL_LUNCH,
    evening: [
      'SNACKS|BUTTER COOKIES|MIXED VEG BAJJI|SPINACH & CHEESE FATAYER|MEDU PAKORA|ALOO BUN|JAM DROP COOKIES|GARLIC BREAD',
      'BEVERAGE|ICED TEA|KESAR MILK|BUTTER MILK|BADAM MILK|CHOCOLATE MILK|COLD COFFEE|DATES MILK',
      'SOUP/MILK|DAL SHORBA|CREAM OF CARROT SOUP|CREAM OF BROCCOLI SOUP|CREAM OF TOMATO SOUP|||',
      'BREAD|BREAD ROLL|BREAD ROLL|MULTIGRAIN BREAD ROLL|MULTIGRAIN BREAD ROLL|||',
    ],
    dinner: [
      'SALAD|WALDROF SALAD|COLESLAW SALAD||KIMCHI SALAD|QUINOA SALAD|PANZANELLA SALAD|CHOP ONION SALAD',
      'BREAD|CHAPATI|VEG BURGER||AMRITSARI KULCHA|CHAPATI||MULTIGRAIN BREAD ROLL',
      'BREAD||FRENCH FRIES||RASAM||GARLIC TOAST|RASAM',
      'CONTI MAIN|MAC & CHEESE WITH MUSHROOM|PANEER BHURJI||CHILLY PANEER|ROASTED POTATO WEDGES|VEG MANCHURIAN|VEG CROQUETTES',
      'INDIAN VEG|METHI MUTTER MASALA|MUSHROOM & CAPSICUM MASALA||JAIPHALI ALOO|SOYA CHUNKS MASALA|ALOO CAPSICUM MASALA|CABBAGE FOOGATH',
      'LENTIL|DAL DHOKLI|KHAR DAL||GAHAT DAL|DAL MAKHANI|HAWAIJAR DAL|GONGURA DAL',
      'NON-VEG|TANDOORI CHICKEN|CHICKEN BURGER||GRILLED FISH WITH LEMON BUTTER SAUCE|CHICKEN KHEEMA MUTTER|CHICKEN FRIED RICE|CHICKEN CUTLETS',
      'RICE|||||VEG FRIED RICE|',
      'DESSERT|EGGLESS COFFEE CAKE|MOONG DAL PAYASAM||DRY JAMUN|CHOCO BALLS|BROWNIE|ICE CREAM',
      'BEVERAGE|BOURNVITA|HOT CHOCOLATE||BOOST|PLAIN MILK|HOT CHOCOLATE|BOOST',
    ],
    dinnerCurd: every('ACCOMPANIMENTS', 'CURD', WED),
  },
  {
    week: 2,
    weekStart: '2026-10-12',
    breakfast: [
      'EARLY SNACK|HOT CHOCOLATE|BOOST|PLAIN HOT MILK|HOT CHOCOLATE|PLAIN HOT MILK||',
      'EARLY SNACK|RAGI JAGGERY COOKIES|KHAMAN DHOKLA|BROWN BREAD SANDWICH|MULTIGRAIN SWIRL|ALOO TIKKI||',
      'MAIN|IDLY|PANEER PARATHA|PLAIN UTTAPAM|METHI THEPLA|POORI|RAVA IDLY|MASALA DOSA',
      'MAIN|MEDU VADA|PICKLE|SAMBAR|BAKED BEANS||BOMBAY SAGU|ALOO PALYA',
      'MAIN|SAMBAR|TAMATAR KI SUBZI|CHUTNEY|PICKLE|RAJASTANI ALOO CURRY|CHUTNEY|SAMBAR',
      'MAIN|CHUTNEY|CURD||CURD|||CHUTNEY',
      'CONTI|FRENCH TOAST|AMERICAN PAN CAKE|FRENCH TOAST|AMERICAN PAN CAKE|FRENCH TOAST|WAFFLE|VEG SANDWICH',
      'CONTI|MAPLE SYRUP|MAPLE SYRUP|MAPLE SYRUP|CHOCOLATE SYRUP|MAPLE SYRUP|MAPLE SYRUP|',
      'EGG|CHEESE OMELETTE|MASALA OMELETTE|SCRAMBLED EGG|MASALA OMELETTE|CHEESE OMELETTE|BOILED EGG|FRIED EGG',
      'CEREAL|HASH BROWN POTATOES|CORN FLAKES|HASH BROWN POTATOES|CORN FLAKES|CORN FLAKES|CORN FLAKES|CORN FLAKES',
      'CEREAL|MUESLI|MUESLI|CORN FLAKES|CHOCO FLAKES|MUESLI|MUESLI|MUESLI',
      'FRUIT|PAPAYA|BANANA|PAPAYA|BANANA|PAPAYA|FRESH FRUIT JUICE|FRESH FRUIT JUICE',
      BREAKFAST_BREAD,
      'ACCOMPANIMENTS|BUTTER|BUTTER /CHEESE SPREAD|BUTTER /CHEESE SPREAD|BUTTER /CHEESE SPREAD|BUTTER|BUTTER|BUTTER',
      'BEVERAGE|HOT CHOCOLATE|BOOST|HOT CHOCOLATE|BOOST|HOT CHOCOLATE|BOOST|HOT CHOCOLATE',
    ],
    morning: ['JUICE|MINT LEMON JUICE|ICED TEA|WATERMELON LEMON SARBATH|GINGER LEMON JUICE|ICED TEA|SWEET N SALT LEMON JUICE|LEMON ICE TEA'],
    lunch: [
      'SOUP||CORN CHOWDER|RASAM|TOM YUM SOUP||TOMATO SOUP WITH CROUTONS|RASAM',
      'SALAD|KOSUMBARI|GREEN SALAD|TOSSED SALAD|BLACK CHANA SUNDAL||RAINBOW CRUNCH SALAD|COUSCOUS SALAD',
      'BREAD|CHAPATI|CHAPATI|CHAPATI|CHAPATI||ALOO PARATHA|VEG BURRITOS',
      'BREAD||BROWN ONION BREAD ROLL||MULTIGRAIN BREAD ROLL||MULTIGRAIN BREAD ROLL|CHICKEN BURRITOS',
      'CONTI MAIN|SICHUAN DRY POT POTATOES|PENNE PUTTANESCA|BUTTERED VEG|MAC & CHEESE WITH MUSHROOM||TURKISH SAKSUKA|ALOO TINDLY FRY',
      'INDIAN VEG|PANEER BUTTER MASALA|CHANA PALAK|RAJMAH MASALA|KOBI BHATATA NU SHAAK||MUTTER PANEER|MAAKOUDA',
      'LENTIL|DAL MAKHANI|ARAHAR DAL|MASALA DAL FRY|KHASI STYLE DAL||DAL MUGHLAI|PALAK DAL',
      'DESSERT|JELLY|MANGO BURFI|GULAB JAMUN|ICE CREAM||ZAUQ-E-SHAHI|MISSISSIPPI MUD CAKE',
    ],
    lunchSpecial: 'INTERNATIONAL LUNCH SERIES - PORTUGUESE SPECIAL LUNCH',
    evening: [
      'SNACKS|DATES & RAISINS CAKE|MASALA VADA|CHOCOLATE DONUTS|ALOO BONDA|MASALA ROLLS|DILPASAND|PANEER & CAPSICUM PUFFS',
      'BEVERAGE|ICED TEA|CHOCOLATE MILK|BUTTER MILK|STRAWBERRY MILK|BADAM MILK|COLD COFFEE|BANANA MILK',
      'SOUP/MILK|CREAM OF SPINACH|CABBAGE CHOWDER|TOMATO SHORBA|CASHEW CORIANDER SOUP|||',
      'BREAD|BREAD ROLL|BREAD ROLL|MULTIGRAIN BREAD ROLL|MULTIGRAIN BREAD ROLL|||',
    ],
    dinner: [
      'SALAD|GRILLED VEG SALAD|TABBOULEH||POTATO CORN SALAD|CARROT & RAISIN SALAD|ALOO CHAAT|GREEN SALAD',
      'BREAD|CHAPATI|MULTIGRAIN PARATHA||CHAPATI|PAN CON TOMATO||CHAPATI',
      'BREAD||GUJARATI UNDHIYU||TARTAR SAUCE|SPAGHETTI|VEG BIRYANI|BREAD ROLL',
      'CONTI MAIN|VEG SLIDERS|VEG VOL AU VENT||FRENCH FRIES|VEG BOLOGNESE SAUCE|ASIAN STIR FRY VEG|VEG & PANEER BAO BUNS',
      'INDIAN VEG|VEG KOLHAPURI|PUNJABI ALOO GOBI||HYDERABADI BAGARA BAINGAN|VEG JAIPURI|MIRCHI KA SALAN|GOBI MUTTER',
      'LENTIL|DAL MAHARAJA|DAL MAKHANI||DAL TAMATAR|MADRA DAL|DALCHA|RASAM / DAL DANIYA',
      'NON-VEG|CHICKEN SLIDERS|EGG MASALA||CRUMB FRIED FISH|CHICKEN BOLOGNESE|CHICKEN DUM BIRYANI|CHICKEN BAO BUNS',
      'DESSERT|EGGLESS BUTTERSCOTCH PASTRY|CHAMPAKALI||STRAWBERRY SWISS ROLL|SEMIYA PAYASAM|ICE CREAM|WHITE PUMPKIN HALWA',
      'BEVERAGE|HOT CHOCOLATE|BOOST||BOURNVITA|HOT CHOCOLATE|BOOST|BOURNVITA',
    ],
    dinnerCurd: 'ACCOMPANIMENTS|CURD|CURD||CURD|CURD|RAITA|CURD',
  },
  {
    week: 3,
    weekStart: '2026-10-26',
    breakfast: [
      'EARLY SNACK|BOOST|HOT CHOCOLATE|PLAIN HOT MILK|HOT CHOCOLATE|PLAIN HOT MILK||',
      'EARLY SNACK|DAL MATRI|WHOLE WHEAT LAVASH STICK|WHOLE WHEAT BANANA CAKE|HONEY OATS COOKIES|BROWN BREAD SANDWICH||',
      'MAIN|IDLY|GOBI PARATHA|ADAI|RAVA KITCHADI|POORI|MASALA SANNAS|MASALA DOSA',
      'MAIN|MEDU VADA|PICKLE|AVIAL|CAPSICUM BAJJI||SAMBAR|ALOO PALYA',
      'MAIN|SAMBAR|CURD|CHUTNEY|BAKED BEANS|ALOO BHAJI|CHUTNEY|SAMBAR',
      'MAIN|CHUTNEY|||CHUTNEY|||CHUTNEY',
      'CONTI|FRENCH TOAST|AMERICAN PAN CAKE|FRENCH TOAST|AMERICAN PAN CAKE|FRENCH TOAST|VEG SANDWICH|WAFFLE',
      'CONTI|MAPLE SYRUP|MAPLE SYRUP|MAPLE SYRUP|CHOCOLATE SYRUP|MAPLE SYRUP||MAPLE SYRUP',
      'EGG|MASALA OMELETTE|CHEESE OMELETTE|FRIED EGG|CHEESE OMELETTE|MASALA OMELETTE|SPANISH OMELETTE|BOILED EGG',
      'CEREAL|HASH BROWN POTATO|CORN FLAKES|CORN FLAKES|HASH BROWN POTATO|CORN FLAKES|CORN FLAKES|CORN FLAKES',
      'CEREAL|CORN FLAKES/MUESLI|MUESLI|MUESLI|CHOCO FLAKES|MUESLI|MUESLI|MUESLI',
      'FRUIT|PAPAYA|BANANA|PAPAYA|BANANA|PAPAYA|FRESH FRUIT JUICE|FRESH FRUIT JUICE',
      BREAKFAST_BREAD,
      'ACCOMPANIMENTS|BUTTER /CHEESE SPREAD|BUTTER|BUTTER /CHEESE SPREAD|BUTTER|BUTTER|BUTTER /CHEESE SPREAD|BUTTER',
      'BEVERAGE|BOOST|HOT CHOCOLATE|BOOST|HOT CHOCOLATE|BOOST|HOT CHOCOLATE|BOOST',
    ],
    morning: ['JUICE|SWEET N SALT LEMON JUICE|ICED TEA|WATERMELON & LEMON SHARBAT|MINT LEMON JUICE|ICED TEA|GINGER LEMON JUICE|MANGO JUICE'],
    lunch: [
      'SOUP||MINESTRONE SOUP|TOMATO SOUP|HOT & SOUR VEG SOUP||MULLIGATAWNY SOUP|RASAM',
      'SALAD|BARLEY SALAD|GREEN BEAN SALAD|ITALIAN DELI SALAD|GREEN SALAD||TEX MEX STYLE SWEETCORN SALAD|LACCHA ONION SALAD',
      'BREAD|CHAPATI|CHAPATI|CHAPATI|CHAPATI||PANEER PARATHA|BHATURA',
      'BREAD||MULTIGRAIN BREAD ROLL|BREAD ROLL|MULTIGRAIN BREAD ROLL||MULTIGRAIN BREAD ROLL|VEG TAGINE',
      'CONTI MAIN|PASTA ALFREDO|VEG CUTLETS|CURRIED NOODLES|BAKED VEG FLORENTINE||OVEN ROAST POTATOES|TAI PAI CHICKEN',
      'INDIAN VEG|DUM ALOO BANARASI|CHOLE MASALA|PANEER MAKHANI|KADI PAKODI||PHOOL MAKHANA MASALA|PINDI CHOLE',
      'LENTIL|AMTI DAL|SAMBAR|DAL TADKEWALI|DAL BHUKARA||MANGODI KI DAL|HAWAIJOR DAL',
      'DESSERT|ICE CREAM|COLUMBIAN COFFEE CAKE|MOTICHOOR LADOO|APPLE CRUMBLE||RASMALAI|DHARWAD PEDA',
    ],
    lunchSpecial: SPECIAL_LUNCH,
    evening: [
      'SNACKS|CINNAMON ROLL|CHOCOCHIP MUFFINS|CHEESE PIZZA|ONION PAKORA|CHOCOLATE CROISSANTS|CINNAMON DONUTS|MADDUR VADA',
      'BEVERAGE|ICED TEA|CHOCOLATE MILK|BUTTER MILK|DATES MILK|BANANA MILK|COLD COFFEE|KESAR MILK',
      'SOUP/MILK|LEEKS POTATO SOUP|CREAM OF SPINACH SOUP|TOMATO BASIL BROTH|PUMPKIN & ROASTED GARLIC SOUP|||',
      'BREAD|BREAD ROLL|BREAD ROLL|MULTIGRAIN BREAD ROLL|MULTIGRAIN BREAD ROLL|||',
    ],
    dinner: [
      'SALAD|FATTOUSH SALAD|CAPRESE SALAD||KAREDOK SALAD|SALAD ZANZIBAR|ASIAN SESAME SALAD|GREEN SALAD',
      'BREAD|BUTTER NAAN|CHAPATI||CHAPATI|||LACHHA PARATHA',
      'BREAD||GARLIC BREAD|||PANEER BIRYANI|SAUTEED VEGETABLES|',
      'CONTI MAIN|MASHED POTATO|HUMMUS||SOYA MUTTER MASALA|TAWA SUBZI|MARGHERITA PIZZA|MIXED VEG PORIYAL',
      'INDIAN VEG|PANEER JALFREZI|RAJMAH MASALA||INDONESIAN VEG FRIED RICE|BAGARA BAINGAN|MAHARASHTRIAN USAL|ALOO GOBI MASALA',
      'LENTIL|DAL MAKHANI|DAL PAKHWAN||DOSAKAYA PAPPU|DALCHA|AMRITSARI DAL|KATHIAWADI DAL',
      'LENTIL||||||RASAM|RASAM',
      'NON-VEG|ASIAN STYLE CHICKEN & BROCCOLI|CHICKEN TENDERS||CHICKEN MAKHANI|MUTTON BIRYANI|CHICKEN PIZZA|CHICKEN KORMA',
      'DESSERT|SABUDANA KHEER|JALEBI||EGGLESS BLACK FOREST CAKE|KALAKAND|ICE CREAM|MOONG DAL HALWA',
      'BEVERAGE|HOT CHOCOLATE|BOURNVITA||PLAIN MILK|BOOST|BOURNVITA|HOT CHOCOLATE',
    ],
    dinnerCurd: 'ACCOMPANIMENTS|CURD|CURD||CURD|RAITA|CURD|CURD',
  },
]

function addRows(days, rows, section) {
  for (const row of rows) {
    const [category, ...cells] = row.split('|')
    cells.forEach((text, d) => {
      const t = text.trim()
      if (t) days[d].push({ text: t, category, section })
    })
  }
}

function build(raw) {
  const days = Object.fromEntries(Array.from({ length: 7 }, (_, d) => [d, []]))
  addRows(days, [...raw.breakfast, ...BREAKFAST_END], 'breakfast')
  addRows(days, [...raw.morning, ...MORNING_END], 'morning')
  addRows(days, [...raw.lunch, ...LUNCH_END], 'lunch')
  days[4].push({
    text: raw.lunchSpecial,
    category: 'LUNCH',
    section: 'lunch',
    special: true,
  })
  addRows(days, raw.evening, 'evening')
  addRows(days, [...raw.dinner, ...dinnerEnd(raw.dinnerCurd), every('BEVERAGE', 'COFFEE', WED)], 'dinner')
  days[2].push({
    text: SPECIAL_DINNER,
    category: 'DINNER',
    section: 'dinner',
    special: true,
  })
  return {
    id: `school-${raw.weekStart}`,
    weekStart: raw.weekStart,
    week: raw.week,
    title: `WEEK ${raw.week} - CYCLIC MENU 2026-2027`,
    builtin: true,
    days,
  }
}

export const SCHOOL_MENUS = RAW.map(build)

/** Built-in weeks plus uploads; an upload for the same week wins. */
export function withSchoolMenus(uploaded = []) {
  const taken = new Set(uploaded.map((m) => m.weekStart))
  return [...SCHOOL_MENUS.filter((m) => !taken.has(m.weekStart)), ...uploaded]
}
